
services:
       
  account:
    build:
      context: .
      dockerfile: Dockerfile
    image: account:0.0.1
    container_name: account
    env_file:
      - .env.production
    volumes:
      - ./frontend/assets/domains/:/srv/cf.account/frontend/assets/domains
    environment:
      NODE_ENV: "production"
      PORT: ${PORT:-2202}
    ports:
      - "127.0.0.1:2202:2202"
