
services:
       
  account:
    build:
      context: .
      dockerfile: Dockerfile
    image: account:0.0.1
    container_name: account
    volumes:
      - .:/srv/cf.account/
      - /srv/cf.account/node_modules
    network_mode: host
    environment:
      NODE_ENV: "production"
      PORT: ${PORT:-2202}
    ports:
      - "127.0.0.1:2202:2202"
