FROM node:18-alpine

CMD mkdir /srv/cf.account

COPY ["package.json","/srv/cf.account/"]

WORKDIR /srv/cf.account

RUN npm install

COPY [".", "/srv/cf.account/"]

EXPOSE $PORT

CMD [ "npm", "run", "dev" ]
