
services:
       
  account:
    build:
      context: .
      dockerfile: Dockerfile
    image: account:0.0.1
    container_name: account
    volumes:
      - .:/srv/cf.account/
      - /srv/cf.account/node_modules
    environment:
      NODE_ENV: "production"
       PORT: ${PORT:-2202}
    ports:
      - "${PORT:-2202}:2202"
      
networks:
  default:
    external:
      name: jotace
